[module]
  [module.hugoVersion]
    min = "0.64.1"
    extended = false
  [[module.mounts]]
    source = "config"
    target = "config"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
